baseURL = 'https://freedom.restoringeden.de/'
languageCode = 'en-us'
title = 'PA2BA | Freedom From Porn'
subtitle = 'PA2BA | Freedom From Porn'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "PA2BA | Freedom From Porn"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.de]
    title = "PA2BA | Freedom From Porn"
    weight = 2
    contentDir = "content/de"
  [languages.ml]
    title = "PA2BA | Freedom From Porn"
    weight = 2
    contentDir = "content/ml"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
